name: "Puppeteer Screenshot Action"
description: "Run puppeteer script and generate screenshot"
author: "Benjamin Lannon <benjamin@lannonbr.com>"
runs:
  using: "node12"
  main: "lib/index.js"
inputs:
  url:
    required: true
    description: "The URL you want puppeteer to visit"
  width:
    description: "Desired width of browser viewport (pixels)"
    required: false
    default: 1920
  height:
    description: "Desired height of browser viewport (pixels)"
    required: false
    default: 1080
